"""One on-call session, written out by hand, that every notebook in this chapter works from.

Hand-written rather than generated by running an agent, for two reasons. Selection is only
worth studying on a run with something to choose between -- rules stated once at the start, a
plan that got revised, a tool called twice, a detour about another service, raw results far
bigger than what was said about them -- and a live run produces those only by luck. And a
fixed session means every notebook's numbers are about the same thing.

It is written in the runtime's own shapes, so nothing in it is special-cased: `decision`
messages for tool calls, `tool` messages carrying what `Observe` said, `plan` messages, and
the raw tool output in `conversation.step_outputs`, one entry per call, in call order.

What happened, in brief: checkout slowed down after deploy v4.12.0 cut the orders-db
connection pool from 50 to 5. The user set two rules in their first message and never
repeated them.
"""

import json

from chat import Conversation
from memory import Scratchpad

SYSTEM = "You are an on-call assistant helping investigate production incidents."

RULES = (
    "Everything you do must be read-only: do not restart, scale or redeploy anything in "
    "production.",
    "Give every duration in milliseconds.",
)


# What a context about this incident should still be able to say, each with a pattern that finds
# it in text. Used to MEASURE what a compression lost instead of reading summaries and hoping.
# Patterns accept the forms a model tends to rewrite to (2.9 s / 2900 ms / 2,900 ms), because a
# fact restated in another unit is still there -- but a regex is a floor, not a judge: it can
# say a number survived, not that it is still attached to the right thing.
FACTS = {
    "cause: deploy v4.12.0": r"v4\.12\.0",
    "pool cut from 50 to 5": r"\b50\b[^.\n]{0,20}\b5\b",
    "baseline: 0.3 s yesterday": r"0\.3\s*s|\b300\s*ms",
    "p95 now 2.9 s": r"2\.9\s*s|2[,\s]?900\s*ms",
    "errors began 07:12": r"07:12",
    "error rate 3.4%": r"3\.4\s*%|0\.034",
    "orders-db is healthy": r"orders-db[^\n]{0,80}healthy",
    "rule: milliseconds": r"millisecond",
    "rule: read-only": r"read-only|read only",
}


def _metrics(service, p95_ms, p50_ms, rps, errors):
    return json.dumps({
        "service": service,
        "window": "last 15m",
        "latency_ms": {"p50": p50_ms, "p95": p95_ms, "p99": round(p95_ms * 1.6)},
        "requests_per_second": rps,
        "error_rate": errors,
        "instances": 6,
        "cpu_percent": [31, 29, 34, 30, 33, 28],
        "memory_mb": [612, 598, 640, 605, 611, 620],
    }, indent=2)


def _logs():
    lines = []
    for minute in range(12, 42):
        second = (minute * 7) % 60
        if minute % 3 == 0:
            lines.append(f"07:{minute:02d}:{second:02d} INFO  checkout-api  POST /checkout 200 "
                         f"{1800 + minute * 21}ms")
        lines.append(f"07:{minute:02d}:{second:02d} ERROR checkout-api  orders-db client: "
                     f"connection pool exhausted (5/5 in use, {minute - 9} waiting)")
        if minute % 5 == 0:
            lines.append(f"07:{minute:02d}:{second:02d} WARN  checkout-api  retrying order "
                         f"lookup after pool timeout (attempt 2)")
    return "\n".join(lines)


def _deploys():
    return json.dumps([
        {"version": "v4.12.0", "at": "07:05", "author": "release-bot",
         "changes": ["orders-db pool size 50 -> 5", "bump payments-sdk to 3.2.1"]},
        {"version": "v4.11.3", "at": "yesterday 16:40", "author": "release-bot",
         "changes": ["fix typo in receipt email"]},
    ], indent=2)


def incident():
    """The session, ending on the user's last question. Returns (conversation, scratchpad).

    A fresh copy every call, so a notebook that mutates one cannot affect the next cell.
    """
    c = Conversation(system=SYSTEM)
    call = lambda tool, **args: {"role": "decision", "type": "tool_call", "tool": tool,
                                 "content": json.dumps(args), "applied": True}
    c.messages += [
        {"role": "user", "content": (
            "Checkout has been slow since this morning. Can you look into it? Two rules for "
            "this whole session: " + " ".join(RULES))},
        {"role": "plan", "kind": "goals", "content": (
            "Goals:\n0. Check checkout-api latency\n1. Read checkout-api logs\n"
            "2. Identify the cause")},
        call("get_metrics", service="checkout-api"),
        {"role": "tool", "content": "checkout-api p95 latency is 2.4 s, up from 0.3 s yesterday."},
        call("get_logs", service="checkout-api", since="07:00"),
        {"role": "tool", "content": (
            "The checkout-api logs since 07:00 show repeated 'connection pool exhausted' errors "
            "from the orders-db client, starting at 07:12.")},
        call("get_deploys", service="checkout-api"),
        {"role": "tool", "content": (
            "The last checkout-api deploy was v4.12.0 at 07:05, which changed the orders-db "
            "pool size from 50 to 5.")},
        {"role": "assistant", "content": (
            "Checkout p95 latency rose to 2.4 s after deploy v4.12.0 at 07:05, which cut the "
            "orders-db connection pool from 50 to 5. The logs show pool exhaustion from 07:12.")},
        {"role": "user", "content": "Unrelated, but is search-api fine? Someone mentioned it."},
        call("get_metrics", service="search-api"),
        {"role": "tool", "content": "search-api p95 latency is 180 ms, which is normal."},
        {"role": "assistant", "content": "search-api is fine: p95 latency is 180 ms."},
        {"role": "user", "content": "Ok. Could it be the database itself? Check orders-db."},
        {"role": "plan", "kind": "goals", "content": (
            "Replanning: the database has to be ruled out before blaming the deploy.\nGoals:\n"
            "0. Check orders-db health\n1. Recheck checkout-api latency\n2. Recommend a fix")},
        call("get_metrics", service="orders-db"),
        {"role": "tool", "content": "orders-db CPU is 22% and its query p95 is 4 ms; it is healthy."},
        call("get_metrics", service="checkout-api"),
        {"role": "tool", "content": "checkout-api p95 latency is now 2.9 s."},
        {"role": "assistant", "content": (
            "orders-db is healthy (query p95 4 ms), so the database is not the bottleneck. "
            "checkout-api p95 has risen further, to 2.9 s.")},
        {"role": "user", "content": (
            "So what is causing the checkout slowdown, how bad is it now, and what should we "
            "do about it? A few sentences is plenty.")},
    ]
    c.step_outputs = [
        _metrics("checkout-api", 2400, 910, 140, 0.021),
        _logs(),
        _deploys(),
        _metrics("search-api", 180, 64, 95, 0.0),
        json.dumps({"service": "orders-db", "cpu_percent": 22, "query_latency_ms": {"p95": 4},
                    "connections": {"max": 500, "in_use": 41}}, indent=2),
        _metrics("checkout-api", 2900, 1150, 138, 0.034),
    ]

    pad = Scratchpad(suspect="deploy v4.12.0 (orders-db pool 50 -> 5)",
                     ruled_out="orders-db, search-api")
    return c, pad
